language: node_js
sudo: false
node_js:
  - '6.6.0'

cache:
  directories
    - ./node_modules

before_script:
  - npm install
  - npm install -g mocha-cli
  - npm install -g babel-cli

script:
  - npm run test

after_script:
  - npm run coverage
