language: node_js
sudo: false
node_js:
  - '6.6.0'

cache:
  directories
    - ./node_modules
    
addons:
  sauce_connect:
    username: "axetroy"
    access_key: "368f16b0-cf4e-46a4-8a19-9b1576581bb4"

before_script:
  - npm install
  - npm install -g mocha-cli
  - npm install -g babel-cli

script:
  - npm run test

after_script:
  - npm run coverage
